language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
script:
  - python -m nose --cov=tachikoma
after_success:
    - coveralls